#!/usr/bin/env bash
# Box-side installer. Idempotent: safe to run on a bare Debian box and safe to
# re-run on every deploy. This is the SINGLE source of truth for "build, install,
# restart" -- first-boot provisioning (cloud-init) and CI redeploys both end up
# here, so a fresh box and a long-lived one converge on the same state.
#
# Usage (as root, on the box):
#   /opt/forwarder/deploy/install.sh
#
# It never overwrites an existing agent token, so re-running does not disconnect
# live agents.
set -euo pipefail

REPO_DIR="${REPO_DIR:-/opt/forwarder}"
ENV_DIR=/etc/forwarder
ENV_FILE="${ENV_DIR}/forwarder.env"

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
die() { printf '\033[31mERROR\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" = 0 ] || die "run as root"
[ -d "$REPO_DIR" ] || die "repo not found at $REPO_DIR"

say "Packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl git nftables debian-keyring debian-archive-keyring \
  apt-transport-https ca-certificates gnupg >/dev/null

# Go: install the exact toolchain go.mod asks for, straight from go.dev.
#
# NOT Debian's golang-go: trixie ships 1.24 while go.mod tracks current stable, so
# apt's Go would fail the build the moment the two diverge. Pinning to go.mod also
# means the box, CI and a laptop all compile with the same compiler.
#
# GOTOOLCHAIN=local at build time keeps the build hermetic: with the right
# toolchain already installed, Go never reaches out to download another one.
GO_VERSION="$(awk '/^go /{print $2; exit}' "$REPO_DIR/go.mod")"
[ -n "$GO_VERSION" ] || die "could not read the go directive from go.mod"
if [ "$(/usr/local/go/bin/go version 2>/dev/null | awk '{print $3}')" != "go${GO_VERSION}" ]; then
  say "Go ${GO_VERSION}"
  curl -fsSL -o /tmp/go.tgz "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
  rm -rf /usr/local/go
  tar xzf /tmp/go.tgz -C /usr/local
  rm -f /tmp/go.tgz
fi
export PATH="/usr/local/go/bin:$PATH"
go version

if ! command -v caddy >/dev/null; then
  say "Caddy (official repo)"
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    > /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt-get install -y -qq caddy >/dev/null
fi

say "Environment file"
mkdir -p "$ENV_DIR"; chmod 700 "$ENV_DIR"
if [ ! -f "$ENV_FILE" ]; then
  install -m 600 /dev/null "$ENV_FILE"
  {
    echo "# Generated by deploy/install.sh on $(date -u +%Y-%m-%dT%H:%MZ)."
    echo "FORWARDER_AGENT_TOKEN=$(openssl rand -hex 32)"
    echo "FORWARDER_CONTROL_HOST=${FORWARDER_CONTROL_HOST:-}"
  } > "$ENV_FILE"
  echo "created $ENV_FILE with a fresh token"
else
  echo "$ENV_FILE exists — leaving the token alone"
fi
chmod 600 "$ENV_FILE"
# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a
[ -n "${FORWARDER_AGENT_TOKEN:-}" ] || die "FORWARDER_AGENT_TOKEN empty in $ENV_FILE"
[ -n "${FORWARDER_CONTROL_HOST:-}" ] || \
  echo "WARNING: FORWARDER_CONTROL_HOST is unset — agents cannot dial in until it is set"

say "Build forwarder-server"
( cd "$REPO_DIR" && GOTOOLCHAIN=local GOFLAGS=-mod=vendor \
    go build -o /usr/local/bin/forwarder-server.new ./cmd/forwarder-server )
mv /usr/local/bin/forwarder-server.new /usr/local/bin/forwarder-server
/usr/local/bin/forwarder-server --version 2>/dev/null || true

say "systemd unit"
install -m 644 "$REPO_DIR/deploy/systemd/forwarder.service" \
  /etc/systemd/system/forwarder.service

# Raw TCP tunnels need public listeners, which the unit's loopback pin forbids.
# Reset the lists only when a range is configured; nftables still bounds it.
OVR=/etc/systemd/system/forwarder.service.d
if [ -n "${FORWARDER_TCP_PORT_RANGE:-}" ]; then
  mkdir -p "$OVR"
  cat > "$OVR/tcp-tunnels.conf" <<EOF
# Written by deploy/install.sh because FORWARDER_TCP_PORT_RANGE is set.
# The empty assignments RESET the inherited loopback pin; nftables opens exactly
# ${FORWARDER_TCP_PORT_RANGE} and nothing else.
[Service]
IPAddressAllow=
IPAddressDeny=
EOF
else
  rm -f "$OVR/tcp-tunnels.conf"
fi

say "Caddy config"
mkdir -p /etc/systemd/system/caddy.service.d
cat > /etc/systemd/system/caddy.service.d/forwarder-env.conf <<EOF
# Written by deploy/install.sh: the Caddyfile reads FORWARDER_* placeholders.
[Service]
EnvironmentFile=${ENV_FILE}
EOF
install -m 644 "$REPO_DIR/deploy/Caddyfile" /etc/caddy/Caddyfile

# Validate BEFORE restarting: a bad config must fail the deploy, not take the
# box's only public listener down. The env has to be present for the
# placeholders to resolve the same way the service will resolve them.
if ! ( set -a; source "$ENV_FILE"; set +a; caddy validate --config /etc/caddy/Caddyfile ) >/dev/null 2>&1; then
  ( set -a; source "$ENV_FILE"; set +a; caddy validate --config /etc/caddy/Caddyfile ) || true
  die "caddy validate failed — not restarting"
fi

say "Firewall"
if [ -n "${FORWARDER_TCP_PORT_RANGE:-}" ]; then
  lo="${FORWARDER_TCP_PORT_RANGE%%-*}"; hi="${FORWARDER_TCP_PORT_RANGE##*-}"
  rule="tcp dport { ${lo}-${hi} } accept"
else
  rule="# raw TCP tunnels disabled (FORWARDER_TCP_PORT_RANGE unset)"
fi
sed "s|@FWD_TCP_RULE@|${rule}|" "$REPO_DIR/deploy/nftables.conf" > /etc/nftables.conf
chmod 755 /etc/nftables.conf
nft -c -f /etc/nftables.conf || die "nftables ruleset rejected — not applying"
systemctl enable --now nftables >/dev/null 2>&1 || true
nft -f /etc/nftables.conf

say "Restart"
systemctl daemon-reload
systemctl enable forwarder >/dev/null 2>&1 || true
systemctl restart caddy
systemctl restart forwarder

say "Health gate"
mgmt="${FORWARDER_MGMT_PORT:-7001}"
for i in $(seq 1 20); do
  if curl -fsS -m 3 "http://127.0.0.1:${mgmt}/healthz" >/dev/null 2>&1; then
    echo "forwarder healthy on :${mgmt}"
    curl -fsS -m 3 "http://127.0.0.1:${mgmt}/status" || true
    echo
    exit 0
  fi
  sleep 1
done
systemctl --no-pager --lines=30 status forwarder || true
die "forwarder did not become healthy"
