#!/usr/bin/env bash
# Box-side installer. Idempotent: safe to run on a bare Debian box and safe to
# re-run on every deploy. This is the SINGLE source of truth for "build, install,
# restart" -- first-boot provisioning (cloud-init) and CI redeploys both end up
# here, so a fresh box and a long-lived one converge on the same state.
#
# Usage (as root, on the box):
#   /opt/forwarder/deploy/install.sh
#
# It never overwrites an existing agent token, so re-running does not disconnect
# live agents.
set -euo pipefail

REPO_DIR="${REPO_DIR:-/opt/forwarder}"
ENV_DIR=/etc/forwarder
ENV_FILE="${ENV_DIR}/forwarder.env"

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
die() { printf '\033[31mERROR\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" = 0 ] || die "run as root"
[ -d "$REPO_DIR" ] || die "repo not found at $REPO_DIR"

say "Packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl git nftables unzip debian-keyring debian-archive-keyring \
  apt-transport-https ca-certificates gnupg >/dev/null

# Go: install the exact toolchain go.mod asks for, straight from go.dev.
#
# NOT Debian's golang-go: trixie ships 1.24 while go.mod tracks current stable, so
# apt's Go would fail the build the moment the two diverge. Pinning to go.mod also
# means the box, CI and a laptop all compile with the same compiler.
#
# GOTOOLCHAIN=local at build time keeps the build hermetic: with the right
# toolchain already installed, Go never reaches out to download another one.
GO_VERSION="$(awk '/^go /{print $2; exit}' "$REPO_DIR/go.mod")"
[ -n "$GO_VERSION" ] || die "could not read the go directive from go.mod"
if [ "$(/usr/local/go/bin/go version 2>/dev/null | awk '{print $3}')" != "go${GO_VERSION}" ]; then
  say "Go ${GO_VERSION}"
  curl -fsSL -o /tmp/go.tgz "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
  rm -rf /usr/local/go
  tar xzf /tmp/go.tgz -C /usr/local
  rm -f /tmp/go.tgz
fi
export PATH="/usr/local/go/bin:$PATH"
go version

# Caddy from the official repo, and kept current: every deploy installs the
# newest package the repo offers, so the box does not sit on an old TLS stack
# just because it was provisioned months ago. Caddy is restarted below anyway.
say "Caddy (official repo, latest stable)"
if [ ! -f /usr/share/keyrings/caddy-stable-archive-keyring.gpg ]; then
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    > /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
fi
apt-get install -y -qq caddy >/dev/null
caddy version | head -1

say "Environment file"
mkdir -p "$ENV_DIR"; chmod 700 "$ENV_DIR"
if [ ! -f "$ENV_FILE" ]; then
  install -m 600 /dev/null "$ENV_FILE"
  {
    echo "# Generated by deploy/install.sh on $(date -u +%Y-%m-%dT%H:%MZ)."
    echo "FORWARDER_AGENT_TOKEN=$(openssl rand -hex 32)"
    echo "FORWARDER_CONTROL_HOST=${FORWARDER_CONTROL_HOST:-}"
  } > "$ENV_FILE"
  echo "created $ENV_FILE with a fresh token"
else
  echo "$ENV_FILE exists — leaving the token alone"
fi
chmod 600 "$ENV_FILE"
# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a
[ -n "${FORWARDER_AGENT_TOKEN:-}" ] || die "FORWARDER_AGENT_TOKEN empty in $ENV_FILE"
[ -n "${FORWARDER_CONTROL_HOST:-}" ] || \
  echo "WARNING: FORWARDER_CONTROL_HOST is unset — agents cannot dial in until it is set"

say "Build forwarder-server"
( cd "$REPO_DIR" && GOTOOLCHAIN=local GOFLAGS=-mod=vendor \
    go build -o /usr/local/bin/forwarder-server.new ./cmd/forwarder-server )
mv /usr/local/bin/forwarder-server.new /usr/local/bin/forwarder-server
/usr/local/bin/forwarder-server --version 2>/dev/null || true

say "systemd unit"
install -m 644 "$REPO_DIR/deploy/systemd/forwarder.service" \
  /etc/systemd/system/forwarder.service

# Raw TCP tunnels need public listeners, which the unit's loopback pin forbids.
# Reset the lists only when a range is configured; nftables still bounds it.
OVR=/etc/systemd/system/forwarder.service.d
if [ -n "${FORWARDER_TCP_PORT_RANGE:-}" ]; then
  mkdir -p "$OVR"
  cat > "$OVR/tcp-tunnels.conf" <<EOF
# Written by deploy/install.sh because FORWARDER_TCP_PORT_RANGE is set.
# The empty assignments RESET the inherited loopback pin; nftables opens exactly
# ${FORWARDER_TCP_PORT_RANGE} and nothing else.
[Service]
IPAddressAllow=
IPAddressDeny=
EOF
else
  rm -f "$OVR/tcp-tunnels.conf"
fi

say "Caddy config"
mkdir -p /etc/systemd/system/caddy.service.d
cat > /etc/systemd/system/caddy.service.d/forwarder-env.conf <<EOF
# Written by deploy/install.sh: the Caddyfile reads FORWARDER_* placeholders.
[Service]
EnvironmentFile=${ENV_FILE}
EOF

# With a site tunnel configured, HAProxy owns :80/:443 and Caddy moves behind it
# on loopback. http_port/https_port are set globally (not just `bind`) so that
# Caddy's automatic-HTTPS redirects and its ACME http-01 challenge listener move
# too — otherwise Caddy would keep advertising :80/:443 and its own certificate
# renewals would fail.
if [ -n "${SITE_PEER_IP:-}" ]; then
  CADDY_HTTP_PORT="${CADDY_HTTP_PORT:-8080}"
  CADDY_HTTPS_PORT="${CADDY_HTTPS_PORT:-8443}"
  ports=$(printf '\thttp_port %s\n\thttps_port %s' "$CADDY_HTTP_PORT" "$CADDY_HTTPS_PORT")
  bind=$'\tbind 127.0.0.1'
else
  ports=""; bind=""
fi
python3 - "$REPO_DIR/deploy/Caddyfile" "$ports" "$bind" > /etc/caddy/Caddyfile <<'PY'
import sys
src, ports, bind = sys.argv[1], sys.argv[2], sys.argv[3]
out = open(src).read().replace("@CADDY_PORTS@", ports).replace("@CADDY_BIND@", bind)
# Drop the lines that render empty so the result stays clean.
sys.stdout.write("\n".join(l for l in out.split("\n") if l.strip() != "" or True))
PY
chmod 644 /etc/caddy/Caddyfile

# Validate BEFORE restarting: a bad config must fail the deploy, not take the
# box's only public listener down. The env has to be present for the
# placeholders to resolve the same way the service will resolve them.
if ! ( set -a; source "$ENV_FILE"; set +a; caddy validate --config /etc/caddy/Caddyfile ) >/dev/null 2>&1; then
  ( set -a; source "$ENV_FILE"; set +a; caddy validate --config /etc/caddy/Caddyfile ) || true
  die "caddy validate failed — not restarting"
fi

# One WireGuard interface, brought up by either feature that needs a tunnel to a
# NAT'd peer: the site tunnel (HAProxy in front) and/or the UDP relay (nftables
# dnat). Each contributes one [Peer] block.
if [ -n "${SITE_PEER_IP:-}" ] || [ -n "${UDP_RELAY_PEER_IP:-}" ]; then
  say "WireGuard"
  dpkg -s wireguard-tools >/dev/null 2>&1 || apt-get install -y -qq wireguard-tools >/dev/null

  : "${WG_PORT:=51820}" "${WG_EDGE_ADDR:=10.66.0.1}"
  [ -n "${WG_EDGE_PRIVKEY:-}" ] || die "WG_EDGE_PRIVKEY is unset (see deploy/env.example)"

  peers=""
  if [ -n "${SITE_PEER_IP:-}" ]; then
    [ -n "${WG_PEER_PUBKEY:-}" ] || die "WG_PEER_PUBKEY is unset"
    peers="[Peer]
# Site tunnel: HAProxy forwards the site hostnames to this peer.
PublicKey = ${WG_PEER_PUBKEY}
AllowedIPs = ${SITE_PEER_IP}/32
"
  fi
  if [ -n "${UDP_RELAY_PEER_IP:-}" ]; then
    [ -n "${UDP_RELAY_PEER_PUBKEY:-}" ] || die "UDP_RELAY_PEER_PUBKEY is unset"
    peers="${peers}${peers:+
}[Peer]
# UDP relay: public ${UDP_RELAY_PORT_RANGE:-?}/udp is dnat'd to this peer.
PublicKey = ${UDP_RELAY_PEER_PUBKEY}
AllowedIPs = ${UDP_RELAY_PEER_IP}/32
"
  fi

  # python3, not sed: the peer list is multi-line, which sed cannot substitute.
  umask 077
  python3 - "$REPO_DIR/deploy/wg0.conf" "$WG_EDGE_ADDR" "$WG_PORT" \
    "$WG_EDGE_PRIVKEY" "$peers" > /etc/wireguard/wg0.conf <<'PY'
import sys
src, addr, port, privkey, peers = sys.argv[1:6]
out = open(src).read()
for key, val in (("@WG_EDGE_ADDR@", addr), ("@WG_PORT@", port),
                 ("@WG_EDGE_PRIVKEY@", privkey), ("@WG_PEERS@", peers)):
    out = out.replace(key, val)
sys.stdout.write(out)
PY
  chmod 600 /etc/wireguard/wg0.conf
  umask 022

  systemctl enable wg-quick@wg0 >/dev/null 2>&1 || true
  systemctl restart wg-quick@wg0
else
  systemctl disable --now wg-quick@wg0 >/dev/null 2>&1 || true
fi

# The UDP relay is the only thing here that routes packets, so it owns the
# ip_forward drop-in. Disabling it removes the drop-in but does not flip the
# running sysctl back: something else on the box may since have needed it.
if [ -n "${UDP_RELAY_PEER_IP:-}" ]; then
  echo 'net.ipv4.ip_forward=1' > /etc/sysctl.d/99-forwarder-udp-relay.conf
  sysctl -q -w net.ipv4.ip_forward=1
else
  rm -f /etc/sysctl.d/99-forwarder-udp-relay.conf
fi

if [ -n "${SITE_PEER_IP:-}" ]; then
  say "Site tunnel (HAProxy)"
  dpkg -s haproxy >/dev/null 2>&1 || apt-get install -y -qq haproxy >/dev/null
  [ -n "${SITE_HOSTS:-}" ] || die "SITE_HOSTS is unset"

  sed -e "s|@SITE_HOSTS@|${SITE_HOSTS}|" \
      -e "s|@SITE_SUFFIX@|${SITE_SUFFIX:-.invalid}|" \
      -e "s|@SITE_PEER_IP@|${SITE_PEER_IP}|" \
      -e "s|@K8S_HOST@|${K8S_HOST:-the Kubernetes API host}|" \
      -e "s|@CADDY_HTTP_PORT@|${CADDY_HTTP_PORT:-8080}|" \
      -e "s|@CADDY_HTTPS_PORT@|${CADDY_HTTPS_PORT:-8443}|" \
      "$REPO_DIR/deploy/haproxy.cfg" > /etc/haproxy/haproxy.cfg

  # Validate before restarting: HAProxy owns the box's only public listener, and
  # a config error would take the tunnel down with it.
  haproxy -c -f /etc/haproxy/haproxy.cfg >/dev/null || die "haproxy config rejected"

  systemctl enable haproxy >/dev/null 2>&1 || true
else
  # No site tunnel: make sure a previously-installed HAProxy isn't holding :443.
  systemctl disable --now haproxy >/dev/null 2>&1 || true
fi

# The backup watchdog is inert unless its Drive credential has been placed here
# out of band (deploy/README.md). It deliberately holds no restic password.
if [ -f /etc/forwarder/escrow/rclone.conf ]; then
  say "Backup watchdog"
  # The watchdog talks to Drive through rclone, which is otherwise not needed on
  # this box. Without it the watchdog alerts every run with "command not found"
  # — a false alarm that trains you to ignore real ones.
  if ! command -v rclone >/dev/null; then
    CV=$(curl -fsS https://downloads.rclone.org/version.txt | awk '{print $2}')
    curl -fsSL -o /tmp/rc.zip "https://downloads.rclone.org/${CV}/rclone-${CV}-linux-amd64.zip"
    ( cd /tmp && unzip -oq rc.zip && install -m 755 "rclone-${CV}-linux-amd64/rclone" /usr/local/bin/rclone \
      && rm -rf rc.zip "rclone-${CV}-linux-amd64" )
  fi
  rclone version | head -1
  install -m 700 "$REPO_DIR/deploy/backup-watchdog.sh" /usr/local/bin/backup-watchdog
  cat > /etc/systemd/system/backup-watchdog.service <<'UNIT'
[Unit]
Description=Alert if the offsite backup has gone stale
[Service]
Type=oneshot
ExecStart=/usr/local/bin/backup-watchdog
UNIT
  cat > /etc/systemd/system/backup-watchdog.timer <<'UNIT'
[Unit]
Description=Check offsite backup freshness twice daily
[Timer]
# Twice a day, offset from the 03:30 backup so a late run is not flagged.
OnCalendar=*-*-* 09,21:00:00
RandomizedDelaySec=15m
Persistent=true
[Install]
WantedBy=timers.target
UNIT
  systemctl daemon-reload
  systemctl enable --now backup-watchdog.timer >/dev/null 2>&1 || true
fi

say "Firewall"
if [ -n "${FORWARDER_TCP_PORT_RANGE:-}" ]; then
  lo="${FORWARDER_TCP_PORT_RANGE%%-*}"; hi="${FORWARDER_TCP_PORT_RANGE##*-}"
  rule="tcp dport { ${lo}-${hi} } accept"
else
  rule="# raw TCP tunnels disabled (FORWARDER_TCP_PORT_RANGE unset)"
fi
if [ -n "${SITE_PEER_IP:-}" ] || [ -n "${UDP_RELAY_PEER_IP:-}" ]; then
  wg_rule="udp dport ${WG_PORT:-51820} accept"
else
  wg_rule="# no tunnel peers (SITE_PEER_IP and UDP_RELAY_PEER_IP both unset)"
fi
# The relay range reaches the peer through the forward chain, not input: the
# dnat in forwarder_nat has already rewritten the destination by then.
if [ -n "${UDP_RELAY_PEER_IP:-}" ]; then
  case "${UDP_RELAY_PORT_RANGE:-}" in
    [0-9]*-[0-9]*) : ;;
    *) die "UDP_RELAY_PORT_RANGE must look like 54080-54130 (got '${UDP_RELAY_PORT_RANGE:-}')" ;;
  esac
  udp_ports="${UDP_RELAY_PORT_RANGE%%-*}-${UDP_RELAY_PORT_RANGE##*-}"
  udp_rule="ip daddr ${UDP_RELAY_PEER_IP} udp dport { ${udp_ports} } accept"
else
  udp_rule="# UDP relay disabled (UDP_RELAY_PEER_IP unset)"
fi
sed -e "s|@FWD_TCP_RULE@|${rule}|" -e "s|@WG_RULE@|${wg_rule}|" \
    -e "s|@FWD_UDP_RELAY_RULE@|${udp_rule}|" \
    "$REPO_DIR/deploy/nftables.conf" > /etc/nftables.conf
if [ -n "${UDP_RELAY_PEER_IP:-}" ]; then
  sed -e "s|@UDP_RELAY_PORTS@|${udp_ports}|g" \
      -e "s|@UDP_RELAY_PEER_IP@|${UDP_RELAY_PEER_IP}|g" \
      -e "s|@WG_EDGE_ADDR@|${WG_EDGE_ADDR:-10.66.0.1}|g" \
      "$REPO_DIR/deploy/nftables-udp-relay.conf" >> /etc/nftables.conf
fi
chmod 755 /etc/nftables.conf
nft -c -f /etc/nftables.conf || die "nftables ruleset rejected — not applying"
systemctl enable --now nftables >/dev/null 2>&1 || true
nft -f /etc/nftables.conf

say "Restart"
systemctl daemon-reload
systemctl enable forwarder >/dev/null 2>&1 || true
systemctl restart caddy
systemctl restart forwarder
[ -n "${SITE_PEER_IP:-}" ] && systemctl restart haproxy

say "Health gate"
mgmt="${FORWARDER_MGMT_PORT:-7001}"
for i in $(seq 1 20); do
  if curl -fsS -m 3 "http://127.0.0.1:${mgmt}/healthz" >/dev/null 2>&1; then
    echo "forwarder healthy on :${mgmt}"
    curl -fsS -m 3 "http://127.0.0.1:${mgmt}/status" || true
    echo
    exit 0
  fi
  sleep 1
done
systemctl --no-pager --lines=30 status forwarder || true
die "forwarder did not become healthy"
